name: habit_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.8.7+54

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
  flutter_slidable: ^4.0.0
  flutter_heatmap_calendar: ^1.0.5
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.0
  google_fonts: ^6.3.0
  showcaseview: ^4.0.1

  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  image_picker: ^1.2.0
  package_info_plus: ^9.0.0
  popover: ^0.3.1
  fl_chart: ^0.69.0

dependency_overrides:
  vector_math: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  image_path: "assets/app_icon.png"
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/

